### ISSUE TITLE
Add the list of available libs and tools available for UI Testing

### ISSUE THREAD

**Issue by Neha** [NoriSte/ui-testing-best-practices#11]
Hello,

Are you planning to add the list of available tools and libs for UI testing also in this? 

We can have a table with heads - component, integration, E2E and tools/libs falling under them.

Thanks,
Neha

**Comment by NoriSte** [comment]
Hi @Neha 
Not really at the moment, I've added an extensive list of tools in another repository of @goldbergyoni that's not published yet (but will be in the near future).
Best
Stefano
