### ISSUE TITLE
Lighthouse Github Actions

### ISSUE THREAD

**Issue by QAInsights** [NoriSte/ui-testing-best-practices#13]
Can we add about Lighthouse Github Actions, probably under monitoring sections?

**Comment by NoriSte** [comment]
HI @QAInsights ! Sure, would you like to write it?
If so, could you share a draft of the contents you'd like to add to that section?
Thank you 😊

**Comment by NoriSte** [comment]
Hi @QAInsights let me know if you want to participate in the project, otherwise, I close this issue 😉feel free to re-open it 🙂
