### ISSUE TITLE
Tip: use Docsify to turn this repo into a website

### ISSUE THREAD

**Issue by dialex** [NoriSte/ui-testing-best-practices#15]
I don't know what is your end goal with this repo, but in case you want to convert it into a website, then you might like [Docsify](https://github.com/docsifyjs/docsify).

_Context: I have a [pet project](https://github.com/dialex/start-testing) that is similar to this one: in my case I'm writing one article per testing concept. I'm using it as a way to learn more about Software Testing._

I have [markdown files](https://github.com/dialex/start-testing/tree/master/docs) just like you. I then use Docsify to serve those `md` files as `html`. That, together with GitHub Pages, gives this end result:

<img width="1439" alt="Screenshot 2020-01-10 at 15 57 30" src="https://user-images.githubusercontent.com/2140450/72170209-650c4480-33c8-11ea-8a0c-71cc672efa2d.png">

I'm pretty happy with the whole setup (easy to get started), and it's way more user friendly than a simple GitHub repo. Just wanted to let you know that the tool exists and is awesome 😁

**Comment by NoriSte** [comment]
Thank you for the suggestion, your repo looks amazing with Docsify 😊 but, above all, congratulations for the contents your writing!! Your willing to improve your testing skills shines through all the references read and cited, kudos!!!
