### ISSUE TITLE
cy.log vs cypress-plugin-steps

### ISSUE THREAD

**Issue by EvgenyOrekhov** [NoriSte/ui-testing-best-practices#43]
In [Keep abstraction low to ease debugging the tests](https://github.com/NoriSte/ui-testing-best-practices/blob/master/sections/generic-best-practices/test-code-with-debugging-in-mind.md) you mention that Cypress doesn't have the concept of "step".
But there is a third-party plugin: https://github.com/filiphric/cypress-plugin-steps
Do you think it would work better than `cy.log()`?
If so, it would be nice to add info about cypress-plugin-steps.

**Comment by NoriSte** [comment]
Hey Evgeny!
I did not know @filiphric's plugin and... I love it!

Thanks for letting us know, I will update the chapter!!! ❤️

**Comment by NoriSte** [comment]
(finally 😅) done in the [latest commit](https://github.com/NoriSte/ui-testing-best-practices/commit/bf6843befc04300e10b6d1a2b6d11d2162c8ff06). Thanks a lot, @EvgenyOrekhov
