### ISSUE TITLE
outline/list of things to test

### ISSUE THREAD

**Issue by chauey** [NoriSte/ui-testing-best-practices#9]
do we have an outline/checklist of test suite hierarchical structure and what things to test?

**Comment by NoriSte** [comment]
HI @chauey 
Not at the moment, would you like to start working on it?

**Comment by chauey** [comment]
I jotted down some ideas, but looking for some of the best examples to analyze.

- navigate/visit
- content contains/check/should
  - (not)contains
  - hidden/visible
  - enabled/disabled
  - active/class
- click
  - button
  - link
- paths
  - happy
  - sad
- CRUD
  - create
  - read
  - update
  - delete
- page basics
  - browser url
  - browser title
  - page title
  - page desc
- form validation
  - simple/single/field
    - required
    - min/max value
    - min/max length
    - data-type
    - pattern
    - email/phone/zip, etc.
    - edge cases -1 0 1 99 100 101
    - label
    - title
    - aria
    - tooltip
  - complex/multi
    - range
  - server
    - validations
    - errors
  - confirm/dialog/modal
    - delete
    - unsaved changes nav away
  - other
    - no error message until submitted at least once
    - button disabled if invalid
    - show/not validations on blur
    - cancel
    - reset
    - refresh
    - browser back/forward button
    - browser refresh
    - mask
    - tooltip
- grid/list
  - page
    - first, prev, next, last
    - \# of total
  - sort
    - columns
    - asc/desc function and arrow
  - filter (form validations)
    - values
    - click, debounce
    - values
    - count
- infrastructure
  - busy indicator
  - notification
  - error
  - logging?
  - auth?
- responsive
  - xs, sm, md, lg, xl
- modules
  - public
  - accounts
  - admin
  - user
  - feature modules
    - ...
- page sections
  - header
    - logo
    - menu
    - logout
    - profile
    - settings
    - language
  - side menu
  - content
  - footer
  - right side
  - ... 
- business
  - personas
  - workflows
- other
  - local storage
  - cookies
  - query strings
  - page/form/component/element
- visual
- xhr/request/response
- config
  - baseUrl, title/name, settings, timeout values, etc.
- system/functional vs regression tests
- cross-browser
  - chrome, firefox, edge, ie, safari, mobile, ...

**Comment by NoriSte** [comment]
Thank you, @chauey I think most of them are features instead of things to be tested. Or, better, features must obviously be tested but I don't think this list could be useful. I think that it could be useful to say how to test them (from the user perspective) and how to not test them (checking for classes, ids, and other de-related stuff). What do you think?
If I have misunderstood what you're meaning I'm sorry, if you prefer to write down part of a chapter to explain me better what are you thinking about, feel free to do that, you're welcome 😊

**Comment by NoriSte** [comment]
@chauey let me know your thoughts, I'll archive the issue in case I don't hear anything from you 🤗

**Comment by chauey** [comment]
Archive is fine, thx
